### ISSUE TITLE
Incorrect values returned when selecting a nested Json value directly

### ISSUE THREAD

**Issue by scarena** [rubrikinc/rbkcli#15] opened 2019-10-20 13:30 UTC
**Expected Behavior**

It's expected that the "select" command would return the correct information independently of the syntax used, for example:

> test rbkcli sla_domain -s id=de7b9926-56dd-4025-90bb-29414c94c46b,replicationSpecs
> [
  {
    "id": "de7b9926-56dd-4025-90bb-29414c94c46b",
    "replicationSpecs": [
      {
        "locationId": "a0e17fe1-2295-451e-b83e-4efb29fdac89",
        "retentionLimit": 86400
      }
    ]
  }
]

and 

>rbkcli sla_domain -s id=de7b9926-56dd-4025-90bb-29414c94c46b,[replicationSpecs][locationId],[replicationSpecs][retentionLimit]
>[
  {
    "id": "de7b9926-56dd-4025-90bb-29414c94c46b",
    "replicationSpecs_locationId": "a0e17fe1-2295-451e-b83e-4efb29fdac89",
    "replicationSpecs_retentionLimit": "a0e17fe1-2295-451e-b83e-4efb29fdac89"
  }
]

**Current Behavior**

At the moment the first syntax returns correctly but the second one returns "N/A" for the nested Json values: 

>rbkcli sla_domain -s id=de7b9926-56dd-4025-90bb-29414c94c46b,[replicationSpecs][locationId],[replicationSpecs][retentionLimit]
>[
  {
    "id": "de7b9926-56dd-4025-90bb-29414c94c46b",
    "replicationSpecs_locationId": "N/A",
    "replicationSpecs_retentionLimit": "N/A"
  }
]

**Failure Information**

No explicit failure information

**Steps to Reproduce**

Just run the commands as shown, to test I was using the local lab Brik

**Comment by Bmanesco** [comment] 2019-12-03 13:45
Hello @scarena, 
Thank you for reporting this!
I investigated the issue and noticed that the unexpected behavior is a mix between lack of documentation around jSON key filtering on **rbkcli** and a missing feature:
- Currently *rbkcli* can only filter results from **direct nested keys** and not results from a **lists of nested keys**. The reason for that is: a list of results is an array, which has a integer index and not a string one as dictionary. 

In the future I am planning to implement list items as well, providing a integer index, such as following:
```
$ rbkcli sla_domain -s id=<id>,[replicationSpecs][1st][locationId]
```
Where you can select explicitly only the first or last of a list (or any specific index that you know of). That would return a new key in the result, such as:
```
[
  {
    "id": "<sla_id>",
    "replicationSpecs_1_locationId": <location_id>
  }
]
```

For now if you want to get a sub value of list attribute of a key you can use -c/--context, which will change the context of the results and then select it, such as following:
```
$ rbkcli sla_domain -f id=<id> -c replicationSpecs -s retentionLimit,locationId
[
  {
    "locationId": "<id>",
    "retentionLimit": 86400
  }
]
```
The difference is that the latter does not have access to any of the parent keys from sla_domain, once now the jSON context has changed to the content of **replicationSpecs**

Please let me know if that clarifies the current behavior and also assists on getting the needed data.

Thank you!

**Comment by Bmanesco** [comment] 2019-12-11 09:58
Closing this issue, let me know if you have any questions.

**Closed by Bmanesco** 2019-12-11 09:58 UTC
Labels: kind-bug
